<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Unit;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pieceUnit = Unit::where('name', 'قطعة')->first();
        $cartonUnit = Unit::where('name', 'كرتونة')->first();

        $products = [
            // Plates & Dishes (أطباق وصحون)
            [
                'name' => 'طبق تقديم دائري 30 سم',
                'barcode' => '6111000001001',
                'large_barcode' => '6111000001001C',
                'sku' => 'PLATE-ROUND-30',
                'min_stock' => 50,
                'avg_cost' => 15.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 25.00,
                'wholesale_price' => 22.00,
                'large_retail_price' => 280.00,
                'large_wholesale_price' => 250.00,
            ],
            [
                'name' => 'صحن طعام سيراميك 25 سم',
                'barcode' => '6111000001002',
                'large_barcode' => '6111000001002C',
                'sku' => 'PLATE-CERAMIC-25',
                'min_stock' => 100,
                'avg_cost' => 12.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 24,
                'retail_price' => 20.00,
                'wholesale_price' => 18.00,
                'large_retail_price' => 450.00,
                'large_wholesale_price' => 400.00,
            ],
            [
                'name' => 'صحن حلويات زجاج 20 سم',
                'barcode' => '6111000001003',
                'large_barcode' => '6111000001003C',
                'sku' => 'PLATE-GLASS-20',
                'min_stock' => 80,
                'avg_cost' => 8.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 15.00,
                'wholesale_price' => 13.00,
                'large_retail_price' => 170.00,
                'large_wholesale_price' => 150.00,
            ],

            // Cups & Mugs (أكواب وفناجين)
            [
                'name' => 'كوب شاي زجاج شفاف',
                'barcode' => '6111000002001',
                'large_barcode' => '6111000002001C',
                'sku' => 'CUP-TEA-GLASS',
                'min_stock' => 150,
                'avg_cost' => 5.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 24,
                'retail_price' => 10.00,
                'wholesale_price' => 8.50,
                'large_retail_price' => 220.00,
                'large_wholesale_price' => 190.00,
            ],
            [
                'name' => 'فنجان قهوة سيراميك',
                'barcode' => '6111000002002',
                'large_barcode' => '6111000002002C',
                'sku' => 'CUP-COFFEE-CERAMIC',
                'min_stock' => 100,
                'avg_cost' => 8.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 15.00,
                'wholesale_price' => 13.00,
                'large_retail_price' => 170.00,
                'large_wholesale_price' => 150.00,
            ],
            [
                'name' => 'كوب ماء زجاج 250 مل',
                'barcode' => '6111000002003',
                'large_barcode' => '6111000002003C',
                'sku' => 'GLASS-WATER-250',
                'min_stock' => 200,
                'avg_cost' => 4.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 24,
                'retail_price' => 8.00,
                'wholesale_price' => 7.00,
                'large_retail_price' => 180.00,
                'large_wholesale_price' => 160.00,
            ],

            // Pots & Pans (أواني طبخ)
            [
                'name' => 'طنجرة ضغط ستانلس 7 لتر',
                'barcode' => '6111000003001',
                'large_barcode' => '6111000003001C',
                'sku' => 'POT-PRESSURE-7L',
                'min_stock' => 20,
                'avg_cost' => 180.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 6,
                'retail_price' => 280.00,
                'wholesale_price' => 250.00,
                'large_retail_price' => 1600.00,
                'large_wholesale_price' => 1450.00,
            ],
            [
                'name' => 'مقلاة تيفال 28 سم',
                'barcode' => '6111000003002',
                'large_barcode' => '6111000003002C',
                'sku' => 'PAN-TEFAL-28',
                'min_stock' => 30,
                'avg_cost' => 85.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 140.00,
                'wholesale_price' => 120.00,
                'large_retail_price' => 1600.00,
                'large_wholesale_price' => 1400.00,
            ],
            [
                'name' => 'حلة طبخ ألومنيوم 5 لتر',
                'barcode' => '6111000003003',
                'large_barcode' => '6111000003003C',
                'sku' => 'POT-ALUMINUM-5L',
                'min_stock' => 40,
                'avg_cost' => 45.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 75.00,
                'wholesale_price' => 65.00,
                'large_retail_price' => 850.00,
                'large_wholesale_price' => 750.00,
            ],

            // Cutlery (أدوات المائدة)
            [
                'name' => 'طقم ملاعق ستانلس 6 قطع',
                'barcode' => '6111000004001',
                'large_barcode' => '6111000004001C',
                'sku' => 'SPOON-SET-6PC',
                'min_stock' => 60,
                'avg_cost' => 35.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 60.00,
                'wholesale_price' => 50.00,
                'large_retail_price' => 680.00,
                'large_wholesale_price' => 580.00,
            ],
            [
                'name' => 'طقم شوك ستانلس 6 قطع',
                'barcode' => '6111000004002',
                'large_barcode' => '6111000004002C',
                'sku' => 'FORK-SET-6PC',
                'min_stock' => 60,
                'avg_cost' => 35.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 60.00,
                'wholesale_price' => 50.00,
                'large_retail_price' => 680.00,
                'large_wholesale_price' => 580.00,
            ],
            [
                'name' => 'طقم سكاكين ستانلس 6 قطع',
                'barcode' => '6111000004003',
                'large_barcode' => '6111000004003C',
                'sku' => 'KNIFE-SET-6PC',
                'min_stock' => 60,
                'avg_cost' => 40.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 70.00,
                'wholesale_price' => 60.00,
                'large_retail_price' => 800.00,
                'large_wholesale_price' => 700.00,
            ],

            // Kitchen Tools (أدوات المطبخ)
            [
                'name' => 'ملعقة طبخ خشبية كبيرة',
                'barcode' => '6111000005001',
                'large_barcode' => '6111000005001C',
                'sku' => 'SPOON-WOOD-LARGE',
                'min_stock' => 100,
                'avg_cost' => 3.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 24,
                'retail_price' => 7.00,
                'wholesale_price' => 6.00,
                'large_retail_price' => 150.00,
                'large_wholesale_price' => 130.00,
            ],
            [
                'name' => 'مصفاة استانلس متوسطة',
                'barcode' => '6111000005002',
                'large_barcode' => '6111000005002C',
                'sku' => 'STRAINER-STEEL-MED',
                'min_stock' => 50,
                'avg_cost' => 18.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 35.00,
                'wholesale_price' => 30.00,
                'large_retail_price' => 400.00,
                'large_wholesale_price' => 350.00,
            ],
            [
                'name' => 'لوح تقطيع بلاستيك كبير',
                'barcode' => '6111000005003',
                'large_barcode' => '6111000005003C',
                'sku' => 'BOARD-PLASTIC-LARGE',
                'min_stock' => 80,
                'avg_cost' => 12.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 25.00,
                'wholesale_price' => 22.00,
                'large_retail_price' => 280.00,
                'large_wholesale_price' => 250.00,
            ],

            // Storage Containers (علب حفظ)
            [
                'name' => 'علبة حفظ بلاستيك 1 لتر',
                'barcode' => '6111000006001',
                'large_barcode' => '6111000006001C',
                'sku' => 'CONTAINER-1L',
                'min_stock' => 120,
                'avg_cost' => 8.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 24,
                'retail_price' => 15.00,
                'wholesale_price' => 13.00,
                'large_retail_price' => 340.00,
                'large_wholesale_price' => 300.00,
            ],
            [
                'name' => 'علبة حفظ زجاج 500 مل',
                'barcode' => '6111000006002',
                'large_barcode' => '6111000006002C',
                'sku' => 'CONTAINER-GLASS-500ML',
                'min_stock' => 100,
                'avg_cost' => 10.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 20.00,
                'wholesale_price' => 17.00,
                'large_retail_price' => 230.00,
                'large_wholesale_price' => 200.00,
            ],
            [
                'name' => 'طقم علب حفظ 3 قطع',
                'barcode' => '6111000006003',
                'large_barcode' => '6111000006003C',
                'sku' => 'CONTAINER-SET-3PC',
                'min_stock' => 60,
                'avg_cost' => 22.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 40.00,
                'wholesale_price' => 35.00,
                'large_retail_price' => 460.00,
                'large_wholesale_price' => 400.00,
            ],

            // Kitchen Gadgets (أدوات متنوعة)
            [
                'name' => 'فتاحة علب كهربائية',
                'barcode' => '6111000007001',
                'large_barcode' => '6111000007001C',
                'sku' => 'OPENER-ELECTRIC',
                'min_stock' => 30,
                'avg_cost' => 55.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 95.00,
                'wholesale_price' => 85.00,
                'large_retail_price' => 1100.00,
                'large_wholesale_price' => 980.00,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
