<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Unit;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pieceUnit = Unit::where('name', 'قطعة')->first();
        $cartonUnit = Unit::where('name', 'كرتونة')->first();

        // Get categories
        $platesCategory = \App\Models\ProductCategory::where('slug', 'plates-dishes')->first();
        $cupsCategory = \App\Models\ProductCategory::where('slug', 'cups-mugs')->first();
        $potsCategory = \App\Models\ProductCategory::where('slug', 'cooking-pots')->first();
        $cutleryCategory = \App\Models\ProductCategory::where('slug', 'cutlery')->first();
        $toolsCategory = \App\Models\ProductCategory::where('slug', 'kitchen-tools')->first();
        $storageCategory = \App\Models\ProductCategory::where('slug', 'storage-containers')->first();
        $miscCategory = \App\Models\ProductCategory::where('slug', 'miscellaneous')->first();

        $products = [
            // Plates & Dishes (أطباق وصحون)
            [
                'category_id' => $platesCategory->id,
                'name' => 'طبق تقديم دائري 30 سم',
                'description' => 'طبق تقديم دائري أنيق بقطر 30 سم، مصنوع من السيراميك الفاخر',
                'image' => 'https://picsum.photos/seed/plate-round-30/600/600',
                'images' => [
                    'https://picsum.photos/seed/plate-round-30-1/600/600',
                    'https://picsum.photos/seed/plate-round-30-2/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000001001',
                'large_barcode' => '6111000001001C',
                'sku' => 'PLATE-ROUND-30',
                'min_stock' => 50,
                'avg_cost' => 15.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 25.00,
                'wholesale_price' => 22.00,
                'large_retail_price' => 280.00,
                'large_wholesale_price' => 250.00,
            ],
            [
                'category_id' => $platesCategory->id,
                'name' => 'صحن طعام سيراميك 25 سم',
                'description' => 'صحن طعام عملي من السيراميك بقطر 25 سم، مناسب للاستخدام اليومي',
                'image' => 'https://picsum.photos/seed/plate-ceramic-25/600/600',
                'images' => [
                    'https://picsum.photos/seed/plate-ceramic-25-1/600/600',
                    'https://picsum.photos/seed/plate-ceramic-25-2/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000001002',
                'large_barcode' => '6111000001002C',
                'sku' => 'PLATE-CERAMIC-25',
                'min_stock' => 100,
                'avg_cost' => 12.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 24,
                'retail_price' => 20.00,
                'wholesale_price' => 18.00,
                'large_retail_price' => 450.00,
                'large_wholesale_price' => 400.00,
            ],
            [
                'category_id' => $platesCategory->id,
                'name' => 'صحن حلويات زجاج 20 سم',
                'description' => 'صحن حلويات أنيق من الزجاج الشفاف بقطر 20 سم',
                'image' => 'https://picsum.photos/seed/plate-glass-20/600/600',
                'images' => [
                    'https://picsum.photos/seed/plate-glass-20-1/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000001003',
                'large_barcode' => '6111000001003C',
                'sku' => 'PLATE-GLASS-20',
                'min_stock' => 80,
                'avg_cost' => 8.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 15.00,
                'wholesale_price' => 13.00,
                'large_retail_price' => 170.00,
                'large_wholesale_price' => 150.00,
            ],

            // Cups & Mugs (أكواب وفناجين)
            [
                'category_id' => $cupsCategory->id,
                'name' => 'كوب شاي زجاج شفاف',
                'description' => 'كوب شاي زجاجي شفاف بتصميم عصري وأنيق',
                'image' => 'https://picsum.photos/seed/cup-tea-glass/600/600',
                'images' => [
                    'https://picsum.photos/seed/cup-tea-glass-1/600/600',
                    'https://picsum.photos/seed/cup-tea-glass-2/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000002001',
                'large_barcode' => '6111000002001C',
                'sku' => 'CUP-TEA-GLASS',
                'min_stock' => 150,
                'avg_cost' => 5.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 24,
                'retail_price' => 10.00,
                'wholesale_price' => 8.50,
                'large_retail_price' => 220.00,
                'large_wholesale_price' => 190.00,
            ],
            [
                'category_id' => $cupsCategory->id,
                'name' => 'فنجان قهوة سيراميك',
                'description' => 'فنجان قهوة فاخر من السيراميك مع صحن',
                'image' => 'https://picsum.photos/seed/cup-coffee/600/600',
                'images' => [
                    'https://picsum.photos/seed/cup-coffee-1/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000002002',
                'large_barcode' => '6111000002002C',
                'sku' => 'CUP-COFFEE-CERAMIC',
                'min_stock' => 100,
                'avg_cost' => 8.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 15.00,
                'wholesale_price' => 13.00,
                'large_retail_price' => 170.00,
                'large_wholesale_price' => 150.00,
            ],
            [
                'category_id' => $cupsCategory->id,
                'name' => 'كوب ماء زجاج 250 مل',
                'description' => 'كوب ماء زجاجي بسعة 250 مل، مثالي للاستخدام اليومي',
                'image' => 'https://picsum.photos/seed/glass-water/600/600',
                'images' => [
                    'https://picsum.photos/seed/glass-water-1/600/600',
                    'https://picsum.photos/seed/glass-water-2/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000002003',
                'large_barcode' => '6111000002003C',
                'sku' => 'GLASS-WATER-250',
                'min_stock' => 200,
                'avg_cost' => 4.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 24,
                'retail_price' => 8.00,
                'wholesale_price' => 7.00,
                'large_retail_price' => 180.00,
                'large_wholesale_price' => 160.00,
            ],

            // Pots & Pans (أواني طبخ)
            [
                'category_id' => $potsCategory->id,
                'name' => 'طنجرة ضغط ستانلس 7 لتر',
                'description' => 'طنجرة ضغط احترافية من الستانلس ستيل بسعة 7 لتر',
                'image' => 'https://picsum.photos/seed/pot-pressure/600/600',
                'images' => [
                    'https://picsum.photos/seed/pot-pressure-1/600/600',
                    'https://picsum.photos/seed/pot-pressure-2/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000003001',
                'large_barcode' => '6111000003001C',
                'sku' => 'POT-PRESSURE-7L',
                'min_stock' => 20,
                'avg_cost' => 180.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 6,
                'retail_price' => 280.00,
                'wholesale_price' => 250.00,
                'large_retail_price' => 1600.00,
                'large_wholesale_price' => 1450.00,
            ],
            [
                'category_id' => $potsCategory->id,
                'name' => 'مقلاة تيفال 28 سم',
                'description' => 'مقلاة غير لاصقة من تيفال بقطر 28 سم',
                'image' => 'https://picsum.photos/seed/pan-tefal/600/600',
                'images' => [
                    'https://picsum.photos/seed/pan-tefal-1/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000003002',
                'large_barcode' => '6111000003002C',
                'sku' => 'PAN-TEFAL-28',
                'min_stock' => 30,
                'avg_cost' => 85.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 140.00,
                'wholesale_price' => 120.00,
                'large_retail_price' => 1600.00,
                'large_wholesale_price' => 1400.00,
            ],
            [
                'category_id' => $potsCategory->id,
                'name' => 'حلة طبخ ألومنيوم 5 لتر',
                'description' => 'حلة طبخ من الألومنيوم المقوى بسعة 5 لتر',
                'image' => 'https://picsum.photos/seed/pot-aluminum/600/600',
                'images' => [
                    'https://picsum.photos/seed/pot-aluminum-1/600/600',
                    'https://picsum.photos/seed/pot-aluminum-2/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000003003',
                'large_barcode' => '6111000003003C',
                'sku' => 'POT-ALUMINUM-5L',
                'min_stock' => 40,
                'avg_cost' => 45.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 75.00,
                'wholesale_price' => 65.00,
                'large_retail_price' => 850.00,
                'large_wholesale_price' => 750.00,
            ],

            // Cutlery (أدوات المائدة)
            [
                'category_id' => $cutleryCategory->id,
                'name' => 'طقم ملاعق ستانلس 6 قطع',
                'description' => 'طقم ملاعق فاخر من الستانلس ستيل يحتوي على 6 قطع',
                'image' => 'https://picsum.photos/seed/spoon-set/600/600',
                'images' => [
                    'https://picsum.photos/seed/spoon-set-1/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000004001',
                'large_barcode' => '6111000004001C',
                'sku' => 'SPOON-SET-6PC',
                'min_stock' => 60,
                'avg_cost' => 35.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 60.00,
                'wholesale_price' => 50.00,
                'large_retail_price' => 680.00,
                'large_wholesale_price' => 580.00,
            ],
            [
                'category_id' => $cutleryCategory->id,
                'name' => 'طقم شوك ستانلس 6 قطع',
                'description' => 'طقم شوك أنيق من الستانلس ستيل يحتوي على 6 قطع',
                'image' => 'https://picsum.photos/seed/fork-set/600/600',
                'images' => [
                    'https://picsum.photos/seed/fork-set-1/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000004002',
                'large_barcode' => '6111000004002C',
                'sku' => 'FORK-SET-6PC',
                'min_stock' => 60,
                'avg_cost' => 35.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 60.00,
                'wholesale_price' => 50.00,
                'large_retail_price' => 680.00,
                'large_wholesale_price' => 580.00,
            ],
            [
                'category_id' => $cutleryCategory->id,
                'name' => 'طقم سكاكين ستانلس 6 قطع',
                'description' => 'طقم سكاكين حادة من الستانلس ستيل يحتوي على 6 قطع',
                'image' => 'https://picsum.photos/seed/knife-set/600/600',
                'images' => [
                    'https://picsum.photos/seed/knife-set-1/600/600',
                    'https://picsum.photos/seed/knife-set-2/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000004003',
                'large_barcode' => '6111000004003C',
                'sku' => 'KNIFE-SET-6PC',
                'min_stock' => 60,
                'avg_cost' => 40.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 70.00,
                'wholesale_price' => 60.00,
                'large_retail_price' => 800.00,
                'large_wholesale_price' => 700.00,
            ],

            // Kitchen Tools (أدوات المطبخ)
            [
                'category_id' => $toolsCategory->id,
                'name' => 'ملعقة طبخ خشبية كبيرة',
                'description' => 'ملعقة طبخ خشبية كبيرة الحجم للاستخدام اليومي',
                'image' => 'https://picsum.photos/seed/spoon-wood/600/600',
                'images' => [
                    'https://picsum.photos/seed/spoon-wood-1/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000005001',
                'large_barcode' => '6111000005001C',
                'sku' => 'SPOON-WOOD-LARGE',
                'min_stock' => 100,
                'avg_cost' => 3.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 24,
                'retail_price' => 7.00,
                'wholesale_price' => 6.00,
                'large_retail_price' => 150.00,
                'large_wholesale_price' => 130.00,
            ],
            [
                'category_id' => $toolsCategory->id,
                'name' => 'مصفاة استانلس متوسطة',
                'description' => 'مصفاة متوسطة الحجم من الستانلس ستيل',
                'image' => 'https://picsum.photos/seed/strainer/600/600',
                'images' => [
                    'https://picsum.photos/seed/strainer-1/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000005002',
                'large_barcode' => '6111000005002C',
                'sku' => 'STRAINER-STEEL-MED',
                'min_stock' => 50,
                'avg_cost' => 18.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 35.00,
                'wholesale_price' => 30.00,
                'large_retail_price' => 400.00,
                'large_wholesale_price' => 350.00,
            ],
            [
                'category_id' => $toolsCategory->id,
                'name' => 'لوح تقطيع بلاستيك كبير',
                'description' => 'لوح تقطيع كبير من البلاستيك المقوى',
                'image' => 'https://picsum.photos/seed/board-plastic/600/600',
                'images' => [
                    'https://picsum.photos/seed/board-plastic-1/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000005003',
                'large_barcode' => '6111000005003C',
                'sku' => 'BOARD-PLASTIC-LARGE',
                'min_stock' => 80,
                'avg_cost' => 12.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 25.00,
                'wholesale_price' => 22.00,
                'large_retail_price' => 280.00,
                'large_wholesale_price' => 250.00,
            ],

            // Storage Containers (علب حفظ)
            [
                'category_id' => $storageCategory->id,
                'name' => 'علبة حفظ بلاستيك 1 لتر',
                'description' => 'علبة حفظ محكمة الإغلاق بسعة 1 لتر',
                'image' => 'https://picsum.photos/seed/container-1l/600/600',
                'images' => [
                    'https://picsum.photos/seed/container-1l-1/600/600',
                    'https://picsum.photos/seed/container-1l-2/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000006001',
                'large_barcode' => '6111000006001C',
                'sku' => 'CONTAINER-1L',
                'min_stock' => 120,
                'avg_cost' => 8.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 24,
                'retail_price' => 15.00,
                'wholesale_price' => 13.00,
                'large_retail_price' => 340.00,
                'large_wholesale_price' => 300.00,
            ],
            [
                'category_id' => $storageCategory->id,
                'name' => 'علبة حفظ زجاج 500 مل',
                'description' => 'علبة حفظ زجاجية بسعة 500 مل مع غطاء محكم',
                'image' => 'https://picsum.photos/seed/container-glass/600/600',
                'images' => [
                    'https://picsum.photos/seed/container-glass-1/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000006002',
                'large_barcode' => '6111000006002C',
                'sku' => 'CONTAINER-GLASS-500ML',
                'min_stock' => 100,
                'avg_cost' => 10.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 20.00,
                'wholesale_price' => 17.00,
                'large_retail_price' => 230.00,
                'large_wholesale_price' => 200.00,
            ],
            [
                'category_id' => $storageCategory->id,
                'name' => 'طقم علب حفظ 3 قطع',
                'description' => 'طقم من 3 علب حفظ بأحجام مختلفة',
                'image' => 'https://picsum.photos/seed/container-set/600/600',
                'images' => [
                    'https://picsum.photos/seed/container-set-1/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000006003',
                'large_barcode' => '6111000006003C',
                'sku' => 'CONTAINER-SET-3PC',
                'min_stock' => 60,
                'avg_cost' => 22.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 40.00,
                'wholesale_price' => 35.00,
                'large_retail_price' => 460.00,
                'large_wholesale_price' => 400.00,
            ],

            // Kitchen Gadgets (أدوات متنوعة)
            [
                'category_id' => $miscCategory->id,
                'name' => 'فتاحة علب كهربائية',
                'description' => 'فتاحة علب كهربائية سهلة الاستخدام',
                'image' => 'https://picsum.photos/seed/opener-electric/600/600',
                'images' => [
                    'https://picsum.photos/seed/opener-electric-1/600/600',
                    'https://picsum.photos/seed/opener-electric-2/600/600',
                ],
                'is_public' => true,
                'barcode' => '6111000007001',
                'large_barcode' => '6111000007001C',
                'sku' => 'OPENER-ELECTRIC',
                'min_stock' => 30,
                'avg_cost' => 55.00,
                'small_unit_id' => $pieceUnit->id,
                'large_unit_id' => $cartonUnit->id,
                'factor' => 12,
                'retail_price' => 95.00,
                'wholesale_price' => 85.00,
                'large_retail_price' => 1100.00,
                'large_wholesale_price' => 980.00,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
